---
server:
  http_listen_port: 3100
memberlist:
  join_members:
    - loki:7946
schema_config:
  configs:
    - from: 2021-08-01
      store: tsdb
      object_store: s3
      schema: v12
      index:
        prefix: index_
        period: 24h
common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      endpoint: minio-dnit-dev.labtrans.ufsc.br:9000
      insecure: false
      bucketnames: loki-data
      access_key_id: 4D876NZOFOV96IJXB56Z
      secret_access_key: oZAOL4PJ6xJ6Btjg8af7oKSeSLti25kiM7ckOsjZ
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist
ruler:
  storage:
    s3:
      bucketnames: loki-ruler